spring:
  profiles:
    include:
      - jwt
      - mail
      - oauth-dev
      - s3
      - db-dev
      - redis
      - log
#  config:
#      import:
#        - application-jwt.yml
#        - application-mail.yml
#        - application-oauth-local.yml
#        - application-s3.yml
#        - application-db-local.yml
#        - application-redis-local.yml
#        - application-log.yml

