spring:
  profiles:
    include: 
      - jwt.yml
      - mail.yml
      - oauth.yml
      - s3.yml
      - db-dev.yml
  # config:
  #   import:
  #     - application-jwt.yml
  #     - application-mail.yml
  #     - application-oauth.yml
  #     - application-s3.yml
  #     - application-db-local.yml
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
