spring:
  profiles:
    active: local
    group:
      common:
        - jwt
        - oauth
        - mail
        - s3
      local:
        - common
        - db-local
      dev:
        - common
        - db-dev
---
spring:
  config:
    activate:
      on-profile: jwt, oauth, mail, db-dev, s3
